### ISSUE TITLE
No installation guide for non-go programmers

### ISSUE THREAD

**Issue by efeakaroz13** [tealeg/csv2xlsx#3]
Hello, I am a python developer and I want to use your software to convert my CSV outputs automatically. But you didn't write how to set the software up using go!

OS: mac os mojave;

**Comment by tealeg** [comment]
That's a very fair point.  This is old, barely maintained software at this point, but I'll consider taking a few minutes to rectify this.

**Comment by efeakaroz13** [comment]
If you can write a new readme it would be very useful; thanks!
